export const GETTERS = {
  USER: {
    TOTAL_BTC: 'USER/TOTAL_BTC',
    TOTAL_USD: 'USER/TOTAL_USD',
    ASSET: 'USER/ASSET',
    ADDRESS: 'USER/ADDRESSES',
  },
  SNAPSHOTS: {
    SNAPSHOTS: 'SNAPSHOTS/SNAPSHOTS'
  }
}

export const MUTATIONS = {
  USER: {
    SET_PROFILE: 'USER/SET_PROFILE',
    SET_ASSETS: 'USER/SET_ASSETS',
    SET_ADDRS: 'USER/SET_ADDR'
  },
  SNAPSHOTS: {
    SET_SNAPSHOTS: 'SNAPSHOTS/SET_SNAPSHOTS',
    REMOVE_SNAPSHOTS: 'SNAPSHOTS/REMOVE_SNAPSHOTS'
  },
  WITHDRAW: {
    SET_ASSET_INDEX: 'WITHDRAW/SET_ASSET_INDEX',
    SET_ASSET_ADDR_INDEX: 'WITHDRAW/SET_ASSET_ADDR_INDEX'
  }
}

export const ACTIONS = {
  USER: {
    GET_PROFILE: 'USER/GET_PROFILE',
    GET_ASSETS: 'USER/GET_ASSETS',
    GET_ADDRS: 'USER/GET_ADDR'
  },
  SNAPSHOTS: {
    GET_SNAPSHOTS: 'SNAPSHOTS/GET_SNAPSHOTS'
  }
}